"""Pytest configuration for test suite."""

import importlib
import os
import sys
from pathlib import Path

import pytest

# Ensure the repo root (for `import tools.x`) AND tools/ itself (for bare
# `import enable_dependabot`) are importable. tools_dir is computed off this
# conftest's own __file__, so it is correct regardless of which subdirectory
# (tests/, tests/unit/, tests/integration/) a test lives in — this is what
# lets root tests move down into tests/unit/ without per-file sys.path fixups
# (#1580).
tools_dir = Path(__file__).parent.parent / "tools"
if str(tools_dir.parent) not in sys.path:
    sys.path.insert(0, str(tools_dir.parent))
if str(tools_dir) not in sys.path:
    sys.path.insert(0, str(tools_dir))


def pytest_configure(config):
    """Configure pytest markers."""
    config.addinivalue_line(
        "markers",
        "adversarial: adversarial tests generated by Gemini Pro (deselect with '-m \"not adversarial\"')",
    )
    config.addinivalue_line(
        "markers",
        "integration: marks tests as integration tests (deselect with '-m \"not integration\"')"
    )
    config.addinivalue_line(
        "markers",
        "e2e: End-to-end tests (deselect with '-m \"not e2e\"')",
    )
    config.addinivalue_line(
        "markers",
        "timeout(seconds): set a timeout for the test (requires pytest-timeout plugin)",
    )


def pytest_sessionstart(session):
    """Remember the operator's home state before any test runs (#3531)."""
    from tests.home_state_guard import snapshot

    session.config._home_state_before = snapshot()


def pytest_sessionfinish(session, exitstatus):
    """Fail the session if any test wrote into the operator's home state (#3531).

    The autouse fixture below redirects every writer this repository knows
    about. This is the check on that knowledge: a new writer, or a test that
    reaches the real paths some other way, fails the run it first appears in,
    with the paths named, rather than filling the operator's resume directory
    and audit log until someone opens them.
    """
    from tests.home_state_guard import changes, snapshot

    before = getattr(session.config, "_home_state_before", None)
    if before is None:
        return
    lines = changes(before, snapshot())
    if not lines:
        return
    reporter = session.config.pluginmanager.get_plugin("terminalreporter")
    if reporter is not None:
        reporter.write_line("")
        reporter.write_line(
            "FAIL: the suite wrote into the operator's home state (#3531). "
            "Redirect the writer through tests/home_state_guard.redirect:"
        )
        for line in lines:
            reporter.write_line("  " + line)
    session.exitstatus = 1


_MODULE_SNAPSHOT_KEYS = [
    "assemblyzero.workflows.testing.nodes.review_test_plan",
    "assemblyzero.core.config",
    "assemblyzero.core.gemini_client",
]


@pytest.fixture(autouse=True)
def _restore_review_test_plan_module():
    """Prevent module-replacement pollution across test files.

    Some tests (test_testing_workflow.py) delete and reimport
    review_test_plan under mocked conditions. Without cleanup the
    stale module stays in sys.modules, breaking @patch targets in
    later test files.
    """
    saved = {k: sys.modules.get(k) for k in _MODULE_SNAPSHOT_KEYS}
    yield
    for key, mod in saved.items():
        if mod is None:
            sys.modules.pop(key, None)
        else:
            sys.modules[key] = mod


@pytest.fixture(autouse=True)
def gate_backoff_waits(monkeypatch):
    """Record the N0c backoff waits suite-wide instead of serving them (#2474).

    The requirements gate now waits out a transient outage before halting, on a
    schedule measured in minutes. Any test that drives the gate to a no-verdict
    outcome would otherwise pay that schedule in real seconds -- four minutes
    per case, in a suite whose whole point is being run often. Several such
    tests already exist in files that know nothing about the backoff, so the
    seam belongs here rather than in the one file that introduced it.

    Yields the list of waits requested, so a test that cares about the schedule
    can assert on it without enduring it.
    """
    waits: list[float] = []
    try:
        module = importlib.import_module(
            "assemblyzero.workflows.requirements.nodes.analyze_requirements"
        )
    except Exception:  # noqa: BLE001 - a test run must not need this module
        yield waits
        return
    monkeypatch.setattr(module, "_sleep", waits.append)
    yield waits


@pytest.fixture(autouse=True)
def no_live_model_calls(request, monkeypatch):
    """A unit test that reaches a real model call fails instantly (#2703).

    Scoped to `tests/unit/` by path. The integration and e2e tiers exist to call
    real services and are left alone; a unit test that genuinely needs a model
    belongs in one of them, and the refusal says so.

    Autouse and unconditional inside that directory, because the incident it
    guards is a test whose author believed the transport was stubbed. A guard
    you have to remember to ask for protects the cases you already thought
    about.
    """
    path = Path(str(request.node.fspath))
    if path.parent.name != "unit":
        yield
        return
    from tests.model_call_guard import install

    install(monkeypatch, request.node.nodeid)
    yield


@pytest.fixture(autouse=True)
def home_state_stays_out_of_home(tmp_path, monkeypatch):
    """Every test's halt snapshots, resume contracts and audit lines land
    under its own tmp_path, never under ~/.assemblyzero/workflow_state or
    ~/.claude/assemblyzero/workflow-audit.jsonl (#3531).

    Autouse and unconditional, for the reason `no_live_model_calls` gives:
    the tests that polluted the operator's home were written by people who
    believed the paths were already redirected. A test that patches one of
    these bindings itself still wins, since its monkeypatch runs later.
    """
    from tests.home_state_guard import redirect

    redirect(monkeypatch, tmp_path / "home-state")


@pytest.fixture(autouse=True)
def no_model_profile_from_the_machine(monkeypatch):
    """A test's model profile comes from the test (#3563).

    ``AZ_MODEL_PROFILE`` outranks the built-in default, so an operator who
    exported it for a comparison roll would otherwise change which provider
    every seat resolves to across the whole suite.

    #3565: the process-wide run profile and the per-call record's sink are
    reset around every test too, so a test that opens a run record or
    announces a profile cannot leak it into the next.
    """
    monkeypatch.delenv("AZ_MODEL_PROFILE", raising=False)
    from assemblyzero.core.model_record import close_sink
    from assemblyzero.core.seats import set_run_profile

    set_run_profile(None)
    close_sink()
    yield
    set_run_profile(None)
    close_sink()


@pytest.fixture
def mock_file_size(monkeypatch):
    """Factory fixture that patches os.path.getsize to return specified sizes for given paths.

    Usage:
        mock_file_size({"/path/to/file.log": 52_428_800})

    Files not in the map delegate to the real os.path.getsize.
    """
    _original_getsize = os.path.getsize

    def _mock(size_map: dict[str, int]) -> None:
        def _patched_getsize(path):
            str_path = str(path)
            if str_path in size_map:
                return size_map[str_path]
            return _original_getsize(str_path)

        monkeypatch.setattr("os.path.getsize", _patched_getsize)

    return _mock