"""Pytest configuration for test suite."""

import importlib
import os
import sys
from pathlib import Path

import pytest

# Ensure the repo root (for `import tools.x`) AND tools/ itself (for bare
# `import enable_dependabot`) are importable. tools_dir is computed off this
# conftest's own __file__, so it is correct regardless of which subdirectory
# (tests/, tests/unit/, tests/integration/) a test lives in — this is what
# lets root tests move down into tests/unit/ without per-file sys.path fixups
# (#1580).
tools_dir = Path(__file__).parent.parent / "tools"
if str(tools_dir.parent) not in sys.path:
    sys.path.insert(0, str(tools_dir.parent))
if str(tools_dir) not in sys.path:
    sys.path.insert(0, str(tools_dir))


def pytest_configure(config):
    """Configure pytest markers."""
    config.addinivalue_line(
        "markers",
        "adversarial: adversarial tests generated by Gemini Pro (deselect with '-m \"not adversarial\"')",
    )
    config.addinivalue_line(
        "markers",
        "integration: marks tests as integration tests (deselect with '-m \"not integration\"')"
    )
    config.addinivalue_line(
        "markers",
        "e2e: End-to-end tests (deselect with '-m \"not e2e\"')",
    )
    config.addinivalue_line(
        "markers",
        "timeout(seconds): set a timeout for the test (requires pytest-timeout plugin)",
    )


_MODULE_SNAPSHOT_KEYS = [
    "assemblyzero.workflows.testing.nodes.review_test_plan",
    "assemblyzero.core.config",
    "assemblyzero.core.gemini_client",
]


@pytest.fixture(autouse=True)
def _restore_review_test_plan_module():
    """Prevent module-replacement pollution across test files.

    Some tests (test_testing_workflow.py) delete and reimport
    review_test_plan under mocked conditions. Without cleanup the
    stale module stays in sys.modules, breaking @patch targets in
    later test files.
    """
    saved = {k: sys.modules.get(k) for k in _MODULE_SNAPSHOT_KEYS}
    yield
    for key, mod in saved.items():
        if mod is None:
            sys.modules.pop(key, None)
        else:
            sys.modules[key] = mod


@pytest.fixture(autouse=True)
def gate_backoff_waits(monkeypatch):
    """Record the N0c backoff waits suite-wide instead of serving them (#2474).

    The requirements gate now waits out a transient outage before halting, on a
    schedule measured in minutes. Any test that drives the gate to a no-verdict
    outcome would otherwise pay that schedule in real seconds -- four minutes
    per case, in a suite whose whole point is being run often. Several such
    tests already exist in files that know nothing about the backoff, so the
    seam belongs here rather than in the one file that introduced it.

    Yields the list of waits requested, so a test that cares about the schedule
    can assert on it without enduring it.
    """
    waits: list[float] = []
    try:
        module = importlib.import_module(
            "assemblyzero.workflows.requirements.nodes.analyze_requirements"
        )
    except Exception:  # noqa: BLE001 - a test run must not need this module
        yield waits
        return
    monkeypatch.setattr(module, "_sleep", waits.append)
    yield waits


@pytest.fixture
def mock_file_size(monkeypatch):
    """Factory fixture that patches os.path.getsize to return specified sizes for given paths.

    Usage:
        mock_file_size({"/path/to/file.log": 52_428_800})

    Files not in the map delegate to the real os.path.getsize.
    """
    _original_getsize = os.path.getsize

    def _mock(size_map: dict[str, int]) -> None:
        def _patched_getsize(path):
            str_path = str(path)
            if str_path in size_map:
                return size_map[str_path]
            return _original_getsize(str_path)

        monkeypatch.setattr("os.path.getsize", _patched_getsize)

    return _mock