"""Test file for Issue #141.

Generated by AssemblyZero TDD Testing Workflow.
Tests for archival of LLD and report files from active/ to done/.
"""

import logging
from datetime import datetime
from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest

from assemblyzero.workflows.testing.audit import TestReportMetadata
from assemblyzero.workflows.testing.nodes.finalize import (
    _archive_workflow_artifacts,
    _generate_summary,
    archive_file_to_done,
    finalize,
)
from assemblyzero.workflows.testing.state import TestingWorkflowState


@pytest.fixture
def temp_repo(tmp_path):
    """Create a temporary repository structure with active/ and done/ directories."""
    active_dir = tmp_path / "docs" / "lld" / "active"
    done_dir = tmp_path / "docs" / "lld" / "done"
    reports_active = tmp_path / "docs" / "reports" / "active"
    reports_done = tmp_path / "docs" / "reports" / "done"
    
    active_dir.mkdir(parents=True)
    done_dir.mkdir(parents=True)
    reports_active.mkdir(parents=True)
    reports_done.mkdir(parents=True)
    
    return tmp_path


@pytest.fixture
def sample_metadata() -> TestReportMetadata:
    """Sample TestReportMetadata for testing."""
    return {
        "issue_number": 141,
        "lld_path": "docs/lld/active/141-fix.md",
        "completed_at": "2025-01-15T10:30:00",
        "test_files": ["tests/test_foo.py", "tests/test_bar.py"],
        "implementation_files": ["assemblyzero/foo.py", "assemblyzero/bar.py"],
        "coverage_achieved": 92.5,
        "coverage_target": 90,
        "total_iterations": 3,
        "test_count": 15,
        "passed_count": 15,
        "failed_count": 0,
        "e2e_passed": True,
    }


# Unit Tests
# -----------

def test_070():
    """
    Empty state | unit | State with no paths | Graceful no-op | No
    exception, empty archival list
    """
    # TDD: Arrange
    state: TestingWorkflowState = {
        "issue_number": 141,
        "lld_path": "",
        "test_report_path": "",
        "implementation_report_path": "",
    }  # type: ignore

    # TDD: Act
    result = _archive_workflow_artifacts(state)

    # TDD: Assert
    assert result["archived"] == []
    assert result["skipped"] == []


def test_100(caplog):
    """
    Exception during file rename | unit | Valid LLD, mock rename to raise
    OSError | None returned, error logged | No exception propagated, log
    contains error message
    """
    # TDD: Arrange
    test_file = Path("/fake/docs/lld/active/141-test.md")
    
    with caplog.at_level(logging.ERROR):
        with patch.object(Path, "exists", return_value=True):
            with patch.object(Path, "rename", side_effect=OSError("Permission denied")):
                # TDD: Act
                result = archive_file_to_done(test_file)

    # TDD: Assert
    assert result is None
    assert "Failed to archive" in caplog.text
    assert "Permission denied" in caplog.text


def test_110(sample_metadata):
    """
    Generate summary | unit | Complete TestReportMetadata dict | Markdown
    summary string | Contains issue number, coverage %, file lists, E2E
    status
    """
    # TDD: Arrange
    # sample_metadata fixture provides complete metadata

    # TDD: Act
    summary = _generate_summary(sample_metadata)

    # TDD: Assert
    assert "# Testing Workflow Summary" in summary
    assert "## Issue #141" in summary
    assert "92.5%" in summary
    assert "test_foo.py" in summary
    assert "assemblyzero/foo.py" in summary
    assert "E2E Status | Passed" in summary
    assert "Total Tests | 15" in summary


def test_120():
    """
    LLD archival fails via wrapper | unit | State with LLD path not in
    active/ | Skipped list includes LLD path | archived=[],
    skipped=[lld_path]
    """
    # TDD: Arrange
    state: TestingWorkflowState = {
        "issue_number": 141,
        "lld_path": "/some/other/path/141-test.md",
        "test_report_path": "",
        "implementation_report_path": "",
    }  # type: ignore

    # TDD: Act
    with patch.object(Path, "exists", return_value=True):
        result = _archive_workflow_artifacts(state)

    # TDD: Assert
    assert result["archived"] == []
    assert "/some/other/path/141-test.md" in result["skipped"]


def test_130():
    """
    Impl report archival fails | unit | State with impl_report path not
    in active/ | Skipped list includes impl report | archived=[],
    skipped=[impl_path]
    """
    # TDD: Arrange
    impl_report_path = "/some/other/path/141-impl.md"
    state: TestingWorkflowState = {
        "issue_number": 141,
        "lld_path": "",
        "test_report_path": "",
        "implementation_report_path": impl_report_path,
    }  # type: ignore

    # TDD: Act
    with patch.object(Path, "exists", return_value=True):
        result = _archive_workflow_artifacts(state)

    # TDD: Assert
    assert result["archived"] == []
    assert impl_report_path in result["skipped"]


# Integration Tests
# -----------------

def test_010(temp_repo, caplog):
    """
    Happy path - LLD archived | integration | State with valid LLD path
    in active/ | LLD moved to done/, path returned | File exists in done/,
    not in active/, log contains success message
    """
    # TDD: Arrange
    active_lld = temp_repo / "docs" / "lld" / "active" / "141-test.md"
    active_lld.write_text("# LLD Content")
    
    with caplog.at_level(logging.INFO):
        # TDD: Act
        result = archive_file_to_done(active_lld)

    # TDD: Assert
    assert result is not None
    done_lld = temp_repo / "docs" / "lld" / "done" / "141-test.md"
    assert done_lld.exists()
    assert not active_lld.exists()
    assert "Archived 141-test.md" in caplog.text


def test_020(temp_repo, caplog):
    """
    Happy path - Reports archived | integration | State with report paths
    in active/ | Reports moved to done/ | Files exist in done/, not in
    active_, log contains success message
    """
    # TDD: Arrange
    report1 = temp_repo / "docs" / "reports" / "active" / "141-impl.md"
    report2 = temp_repo / "docs" / "reports" / "active" / "141-test.md"
    report1.write_text("# Implementation Report")
    report2.write_text("# Test Report")

    state: TestingWorkflowState = {
        "issue_number": 141,
        "lld_path": "",
        "test_report_path": str(report2),
        "implementation_report_path": str(report1),
    }  # type: ignore

    with caplog.at_level(logging.INFO):
        # TDD: Act
        result = _archive_workflow_artifacts(state)

    # TDD: Assert
    assert len(result["archived"]) == 2
    done_report1 = temp_repo / "docs" / "reports" / "done" / "141-impl.md"
    done_report2 = temp_repo / "docs" / "reports" / "done" / "141-test.md"
    assert done_report1.exists()
    assert done_report2.exists()
    assert not report1.exists()
    assert not report2.exists()
    assert "Archived 141-impl.md" in caplog.text


def test_030(caplog):
    """
    LLD not found | integration | State with non-existent LLD path |
    Warning logged, None returned | No exception, log contains warning
    """
    # TDD: Arrange
    non_existent = Path("/fake/path/docs/lld/active/999-missing.md")
    
    with caplog.at_level(logging.WARNING):
        # TDD: Act
        result = archive_file_to_done(non_existent)

    # TDD: Assert
    assert result is None
    assert "File not found for archival" in caplog.text


def test_040(temp_repo, caplog):
    """
    LLD not in active/ | integration | State with LLD in arbitrary path |
    Skip archival, None returned | File unchanged, log indicates skip
    """
    # TDD: Arrange
    arbitrary_path = temp_repo / "some" / "other" / "path" / "141-test.md"
    arbitrary_path.parent.mkdir(parents=True)
    arbitrary_path.write_text("# LLD Content")
    
    with caplog.at_level(logging.INFO):
        # TDD: Act
        result = archive_file_to_done(arbitrary_path)

    # TDD: Assert
    assert result is None
    assert arbitrary_path.exists()  # File unchanged
    assert "not in active/ directory, skipping archival" in caplog.text


def test_050(temp_repo):
    """
    done/ doesn't exist | integration | Valid LLD, no done/ directory |
    done/ created, LLD moved | Directory created, file moved
    """
    # TDD: Arrange
    # Create active/ but remove done/
    active_lld = temp_repo / "docs" / "lld" / "active" / "141-test.md"
    done_dir = temp_repo / "docs" / "lld" / "done"
    active_lld.write_text("# LLD Content")
    
    # Remove done directory to test creation
    import shutil
    if done_dir.exists():
        shutil.rmtree(done_dir)
    
    # TDD: Act
    result = archive_file_to_done(active_lld)

    # TDD: Assert
    assert result is not None
    assert done_dir.exists()  # Directory was created
    done_lld = temp_repo / "docs" / "lld" / "done" / "141-test.md"
    assert done_lld.exists()
    assert not active_lld.exists()


def test_060(temp_repo):
    """
    Destination file exists | integration | LLD exists in both active/
    and done/ | Append timestamp to new name | No overwrite, both files
    preserved
    """
    # TDD: Arrange
    active_lld = temp_repo / "docs" / "lld" / "active" / "141-test.md"
    done_lld = temp_repo / "docs" / "lld" / "done" / "141-test.md"
    
    active_lld.write_text("# New LLD Content")
    done_lld.write_text("# Old LLD Content")
    
    # TDD: Act
    result = archive_file_to_done(active_lld)

    # TDD: Assert
    assert result is not None
    assert result != done_lld  # Different path with timestamp
    assert done_lld.exists()  # Original preserved
    assert done_lld.read_text() == "# Old LLD Content"
    assert result.exists()  # New file created
    assert result.read_text() == "# New LLD Content"
    # Verify timestamp pattern in filename
    assert "141-test-" in str(result)


def test_080(temp_repo, caplog):
    """
    Mixed success | integration | Some files exist, some don't | Archive
    existing, log missing | Partial archival succeeds
    """
    # TDD: Arrange
    existing_file = temp_repo / "docs" / "reports" / "active" / "141-impl.md"
    existing_file.write_text("# Report")

    missing_file = str(temp_repo / "docs" / "reports" / "active" / "999-missing.md")

    state: TestingWorkflowState = {
        "issue_number": 141,
        "lld_path": "",
        "test_report_path": missing_file,
        "implementation_report_path": str(existing_file),
    }  # type: ignore

    with caplog.at_level(logging.WARNING):
        # TDD: Act
        result = _archive_workflow_artifacts(state)

    # TDD: Assert
    assert len(result["archived"]) == 1
    assert len(result["skipped"]) == 1
    assert "File not found for archival" in caplog.text


def test_090(temp_repo):
    """
    Workflow failed - no archival | integration | State with
    workflow_success=False, valid LLD path | No files moved, skip logged |
    Files remain in active/, log indicates skip
    """
    # TDD: Arrange
    active_lld = temp_repo / "docs" / "lld" / "active" / "141-test.md"
    active_lld.write_text("# LLD Content")

    state: TestingWorkflowState = {
        "issue_number": 141,
        "lld_path": str(active_lld),
        "test_report_path": "",
        "implementation_report_path": "",
        "workflow_success": False,
    }  # type: ignore

    # TDD: Act
    result = _archive_workflow_artifacts(state)

    # TDD: Assert
    assert result["archived"] == []
    assert str(active_lld) in result["skipped"]
    assert active_lld.exists()  # File not moved


def test_140(temp_repo):
    """
    E2E evaluation (skip_e2e=False) | integration | State with
    skip_e2e=False, e2e_output="passed" | E2E passed evaluated from output
    | finalize completes, e2e logic exercised
    """
    # TDD: Arrange
    audit_dir = temp_repo / "docs" / "lineage" / "active" / "141-testing"
    audit_dir.mkdir(parents=True)

    state: TestingWorkflowState = {
        "issue_number": 141,
        "repo_root": str(temp_repo),
        "audit_dir": str(audit_dir),
        "lld_path": "",
        "test_report_path": "",
        "implementation_report_path": "",
        "skip_e2e": False,
        "e2e_output": "All tests passed successfully",
        "test_files": ["tests/test_foo.py"],
        "implementation_files": ["assemblyzero/foo.py"],
        "coverage_achieved": 90.0,
        "coverage_target": 90,
        "iteration_count": 1,
        "green_phase_output": "15 passed in 1.23s",
    }  # type: ignore

    # TDD: Act
    with patch("assemblyzero.workflows.testing.nodes.finalize.generate_test_report") as mock_report:
        mock_report.return_value = temp_repo / "docs" / "reports" / "active" / "141-test-report.md"
        result = finalize(state)

    # TDD: Assert
    assert "error_message" in result
    assert result["error_message"] == ""


def test_150(temp_repo):
    """
    Successful workflow with archival | integration | State with
    workflow_success=True (default), valid LLD | LLD archived, archival
    printed | archived_files populated, LLD moved to done/
    """
    # TDD: Arrange
    active_lld = temp_repo / "docs" / "lld" / "active" / "141-test.md"
    active_lld.write_text("# LLD Content")
    audit_dir = temp_repo / "docs" / "lineage" / "active" / "141-testing"
    audit_dir.mkdir(parents=True)

    state: TestingWorkflowState = {
        "issue_number": 141,
        "repo_root": str(temp_repo),
        "audit_dir": str(audit_dir),
        "lld_path": str(active_lld),
        "test_report_path": "",
        "implementation_report_path": "",
        "workflow_success": True,
        "test_files": ["tests/test_foo.py"],
        "implementation_files": ["assemblyzero/foo.py"],
        "coverage_achieved": 92.0,
        "coverage_target": 90,
        "iteration_count": 2,
        "green_phase_output": "10 passed in 0.5s",
        "skip_e2e": True,
    }  # type: ignore

    # TDD: Act
    with patch("assemblyzero.workflows.testing.nodes.finalize.generate_test_report") as mock_report:
        mock_report.return_value = temp_repo / "docs" / "reports" / "active" / "141-test-report.md"
        result = finalize(state)

    # TDD: Assert
    assert "archived_files" in result
    assert len(result["archived_files"]) == 1
    done_lld = temp_repo / "docs" / "lld" / "done" / "141-test.md"
    assert done_lld.exists()
    assert not active_lld.exists()