"""Writes Gemini's adversarial test output to test files.

Issue #352: Multi-Model Adversarial Testing Node (Gemini vs Claude)

Groups test cases by category and writes them as pytest-compatible files
with adversarial identification headers.
"""

import logging
import os
import re
import shutil
import tempfile
from collections import defaultdict

from assemblyzero.workflows.testing.adversarial_state import (
    AdversarialAnalysis,
    AdversarialTestCase,
)

logger = logging.getLogger(__name__)


def write_adversarial_tests(
    analysis: AdversarialAnalysis,
    issue_id: int,
    output_dir: str = "tests/adversarial",
) -> dict[str, str]:
    """Write adversarial test cases to disk as pytest-compatible files.

    Each file follows naming: test_{issue_id}_{category}.py
    Groups test cases by category into separate files.
    Writes to a temp directory first, then performs atomic rename.

    Args:
        analysis: The parsed adversarial analysis from Gemini.
        issue_id: GitHub issue number for file naming.
        output_dir: Directory to write test files to.

    Returns:
        Dictionary of filepath -> file content written.
    """
    test_cases = analysis.get("test_cases", [])
    if not test_cases:
        logger.info("No adversarial test cases to write")
        return {}

    # Group by category
    grouped: dict[str, list[AdversarialTestCase]] = defaultdict(list)
    for tc in test_cases:
        category = _sanitize_category(tc.get("category", "general"))
        grouped[category].append(tc)

    # Write to temp directory first for atomicity
    temp_dir = tempfile.mkdtemp(prefix="adversarial_")
    result: dict[str, str] = {}

    try:
        os.makedirs(output_dir, exist_ok=True)

        for category, cases in grouped.items():
            filename = f"test_{issue_id}_{category}.py"
            filepath = os.path.join(output_dir, filename)
            temp_filepath = os.path.join(temp_dir, filename)

            content = _render_test_file(cases, category, issue_id)

            # Write to temp first
            with open(temp_filepath, "w", encoding="utf-8") as f:
                f.write(content)

            # Atomic move to final location
            shutil.move(temp_filepath, filepath)
            result[filepath] = content

            logger.info(
                "Wrote adversarial test file: %s (%d tests)", filepath, len(cases)
            )

    except Exception:
        logger.exception("Error writing adversarial test files")
        raise
    finally:
        # Clean up temp directory
        if os.path.exists(temp_dir):
            shutil.rmtree(temp_dir, ignore_errors=True)

    return result


def _render_test_file(
    test_cases: list[AdversarialTestCase],
    category: str,
    issue_id: int,
) -> str:
    """Render a list of test cases into a complete pytest file.

    The rendered file begins with a header comment block identifying it
    as adversarial, machine-generated by Gemini Pro.

    Args:
        test_cases: List of test cases for this category.
        category: The adversarial category name.
        issue_id: GitHub issue number.

    Returns:
        Complete Python file content as a string.
    """
    lines: list[str] = []

    # Header comment block
    lines.append("# ADVERSARIAL TEST FILE - Machine-generated by Gemini Pro")
    lines.append(f"# Issue: #{issue_id}")
    lines.append(f"# Category: {category}")
    lines.append("# Generator: assemblyzero adversarial testing node")
    lines.append("# WARNING: Do not manually edit - regenerated on each workflow run")
    lines.append("")

    # Module docstring
    lines.append(f'"""Adversarial {category} tests for issue #{issue_id}.')
    lines.append("")
    lines.append("These tests exercise real code paths with NO mocks.")
    lines.append('"""')
    lines.append("")

    # Test functions
    for tc in test_cases:
        test_code = tc.get("test_code", "").strip()
        if not test_code:
            continue

        # Add a comment with test metadata
        description = tc.get("description", "")
        claim = tc.get("claim_challenged", "")
        severity = tc.get("severity", "medium")
        test_id = tc.get("test_id", "")

        lines.append("")
        if test_id or description:
            lines.append(f"# {test_id}: {description}")
        if claim:
            lines.append(f"# Challenges: {claim}")
        lines.append(f"# Severity: {severity}")

        # Ensure the test code starts with 'def test_'
        if not test_code.startswith("def test_"):
            # Wrap in a function if Gemini didn't provide proper function def
            func_name = f"test_{tc.get('test_id', 'unknown').lower()}"
            func_name = re.sub(r"[^a-z0-9_]", "_", func_name)
            lines.append(f"def {func_name}():")
            # Indent the test code
            for line in test_code.split("\n"):
                lines.append(f"    {line}")
        else:
            lines.append(test_code)

        lines.append("")

    return "\n".join(lines) + "\n"


def _sanitize_category(category: str) -> str:
    """Sanitize category name for use in filenames.

    Converts to lowercase, replaces non-alphanumeric characters with underscores.

    Args:
        category: Raw category string.

    Returns:
        Sanitized category string safe for filenames.
    """
    sanitized = re.sub(r"[^a-z0-9]", "_", category.lower())
    sanitized = re.sub(r"_+", "_", sanitized)  # Collapse multiple underscores
    sanitized = sanitized.strip("_")
    return sanitized or "general"