"""State extensions for adversarial testing node.

Issue #352: Multi-Model Adversarial Testing Node (Gemini vs Claude)
"""

from typing import Literal, TypedDict


class AdversarialTestCase(TypedDict):
    """A single adversarial test case generated by Gemini."""

    test_id: str
    target_function: str
    category: str
    description: str
    test_code: str
    claim_challenged: str
    severity: Literal["critical", "high", "medium"]


class AdversarialAnalysis(TypedDict):
    """Gemini's analysis of implementation vs. LLD claims."""

    uncovered_edge_cases: list[str]
    false_claims: list[str]
    missing_error_handling: list[str]
    implicit_assumptions: list[str]
    test_cases: list[AdversarialTestCase]


class AdversarialNodeState(TypedDict, total=False):
    """State extension for the adversarial testing node."""

    # Inputs (populated by prior nodes)
    implementation_files: dict[str, str]
    lld_content: str
    existing_tests: dict[str, str]
    issue_id: int

    # Outputs (populated by adversarial node)
    adversarial_analysis: AdversarialAnalysis
    generated_test_files: dict[str, str]
    adversarial_verdict: Literal["pass", "fail", "error"]
    adversarial_error: str | None
    adversarial_test_count: int
    adversarial_skipped_reason: str | None


class ValidationResult(TypedDict):
    """Result of adversarial test validation."""

    valid: bool
    errors: list[str]
    warnings: list[str]
    mock_violations: list[str]