"""Canonical git branch helpers (Closes #1758).

The attempt-branch model (operator mandate 2026-07-14): workflows integrate
into the branch the target repo is standing on — never assume main. These
helpers are the one tested answer to "what branch is this repo on, and may
I use it as an integration base?" Per ADR 0224, this deterministic core
lives in small functions with unit tests rather than inline in tools.

Consumers: requirements workflow state creation (#1754), orchestrate()
startup (#1755), run_implement_from_lld branch gate (#1756).
"""

from __future__ import annotations

import re
import subprocess
from pathlib import Path

# Branch names generated by AZ workflows themselves. These are work
# branches, never integration targets: {N}-lld (requirements workflow),
# {N}-implementation (implement tool), issue-{N} (orchestrator impl stage).
_WORK_BRANCH_RE = re.compile(r"^(?:\d+-lld|\d+-implementation|issue-\d+)$")


class GitBranchError(RuntimeError):
    """Raised when a repo's checked-out branch cannot serve as a base."""


def current_branch(repo: Path | str) -> str:
    """Return the branch currently checked out in ``repo``.

    Raises:
        GitBranchError: on git failure or detached HEAD. Callers must NOT
            silently fall back to ``main`` — that reintroduces the
            hardcoded-main behavior the attempt-branch model removes.
    """
    result = subprocess.run(
        ["git", "rev-parse", "--abbrev-ref", "HEAD"],
        cwd=str(repo),
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
    )
    if result.returncode != 0:
        raise GitBranchError(
            f"Cannot determine current branch in {repo}: "
            f"{(result.stderr or '').strip()}"
        )
    branch = result.stdout.strip()
    if not branch or branch == "HEAD":
        raise GitBranchError(
            f"{repo} is on a detached HEAD; check out the integration "
            "branch (e.g. main or speedrun-attempt-N) before running."
        )
    return branch


def is_generated_work_branch(branch: str) -> bool:
    """True if ``branch`` matches an AZ-generated work-branch pattern."""
    return bool(_WORK_BRANCH_RE.fullmatch(branch))


def is_issue_work_branch(branch: str, issue_number: int) -> bool:
    """True if ``branch`` is THIS issue's generated implementation branch.

    Exact match only. The substring test this replaces let
    ``speedrun-attempt-1`` false-match issue #1 and silently run in-place
    with zero commits (#1756).
    """
    return branch in (f"{issue_number}-implementation", f"issue-{issue_number}")


def validate_integration_branch(branch: str) -> None:
    """Reject generated work branches as integration bases.

    Raises:
        GitBranchError: if ``branch`` is a generated work branch.
    """
    if is_generated_work_branch(branch):
        raise GitBranchError(
            f"'{branch}' is a generated work branch, not an integration "
            "branch. Check out the branch you integrate into (e.g. main "
            "or speedrun-attempt-N) and re-run."
        )
