"""A run that accepts a visual baseline emits the rendered image (#2443).

#1902 established the hazard: a visual-regression baseline generated by the
run under test is self-referential. The run renders an image, accepts it as
the baseline, and every later run compares against it -- a systematically
wrong render validates itself and stays green forever. Only a human looking
at a picture breaks the loop, and a sample nobody sees is the current state
this repairs: preserved into the run's lineage, named in the run's output.

Preservation must precede #2048's droppings removal -- isolation and
preservation are both right: the next iteration must not see the files,
the operator must.
"""

import subprocess

import pytest

from assemblyzero.workflows.testing.nodes.verify_phases import (
    _preserve_visual_samples,
    _remove_test_run_droppings,
    _snapshot_untracked,
)

PNG_BYTES = b"\x89PNG\r\n\x1a\n-fake-render-"


def _git(cwd, *args):
    subprocess.run(
        ["git", "-c", "user.email=t@t", "-c", "user.name=t", *args],
        cwd=str(cwd), check=True, capture_output=True, text=True,
    )


@pytest.fixture
def worktree(tmp_path):
    r = tmp_path / "boostgauge"
    r.mkdir()
    _git(r, "init", "-b", "main")
    (r / "src").mkdir()
    (r / "src" / "gauge.py").write_text("# committed\n", encoding="utf-8")
    _git(r, "add", "-A")
    _git(r, "commit", "-m", "base")
    return r


@pytest.fixture
def audit_dir(tmp_path):
    d = tmp_path / "lineage" / "331-testing"
    d.mkdir(parents=True)
    return d


class TestSamplesAreEmitted:
    def test_a_generated_baseline_is_preserved_and_named(self, worktree, audit_dir):
        target = worktree / "tests" / "visual" / "baselines" / "needle_60.png"
        target.parent.mkdir(parents=True)
        target.write_bytes(PNG_BYTES)

        dest, copied = _preserve_visual_samples(worktree, str(audit_dir))

        assert dest == str(audit_dir / "visual-samples")
        assert copied == ["tests/visual/baselines/needle_60.png"]
        saved = audit_dir / "visual-samples" / "tests" / "visual" / "baselines" / "needle_60.png"
        assert saved.read_bytes() == PNG_BYTES, "the pixels must survive verbatim"

    def test_preservation_happens_before_droppings_removal(self, worktree, audit_dir):
        """The real call order: the baseline is iteration poison AND the
        operator's only evidence. Both duties must be met."""
        before = _snapshot_untracked(worktree)
        rendered = worktree / "tests" / "visual" / "baselines" / "face.png"
        rendered.parent.mkdir(parents=True)
        rendered.write_bytes(PNG_BYTES)

        dest, copied = _preserve_visual_samples(worktree, str(audit_dir))
        _remove_test_run_droppings(worktree, before)

        assert not rendered.exists(), "isolation: the dropping is removed"
        saved = audit_dir / "visual-samples" / "tests" / "visual" / "baselines" / "face.png"
        assert saved.read_bytes() == PNG_BYTES, "preservation: the sample survives"
        assert copied == ["tests/visual/baselines/face.png"]

    def test_a_regenerated_tracked_baseline_is_preserved(self, worktree, audit_dir):
        """A committed baseline the run rewrote is as much an acceptance as a
        first-generation one."""
        tracked = worktree / "baseline.png"
        tracked.write_bytes(b"old-render")
        _git(worktree, "add", "-A")
        _git(worktree, "commit", "-m", "old baseline")
        tracked.write_bytes(PNG_BYTES)

        dest, copied = _preserve_visual_samples(worktree, str(audit_dir))

        assert copied == ["baseline.png"]
        assert (audit_dir / "visual-samples" / "baseline.png").read_bytes() == PNG_BYTES


class TestNothingToEmit:
    def test_no_images_means_no_emission(self, worktree, audit_dir):
        dest, copied = _preserve_visual_samples(worktree, str(audit_dir))

        assert (dest, copied) == ("", [])
        assert not (audit_dir / "visual-samples").exists(), (
            "an empty samples dir would read as a run that rendered nothing "
            "worth keeping -- emit nothing instead"
        )

    def test_non_image_droppings_are_not_samples(self, worktree, audit_dir):
        (worktree / ".coverage").write_text("data\n", encoding="utf-8")
        (worktree / "report.txt").write_text("text\n", encoding="utf-8")

        dest, copied = _preserve_visual_samples(worktree, str(audit_dir))

        assert (dest, copied) == ("", [])

    def test_a_missing_audit_dir_is_quiet(self, worktree, tmp_path):
        (worktree / "face.png").write_bytes(PNG_BYTES)

        assert _preserve_visual_samples(worktree, "") == ("", [])
        gone = tmp_path / "never-created"
        assert _preserve_visual_samples(worktree, str(gone)) == ("", [])
