"""Test file for Issue #162.

Generated by AssemblyZero TDD Testing Workflow.
Tests automatic commit and push functionality in requirements workflow.
"""

import pytest
from pathlib import Path
from unittest.mock import Mock, patch
from assemblyzero.workflows.requirements.git_operations import (
    format_commit_message,
    commit_and_push,
    GitOperationError,
)


# Unit Tests
# -----------

def test_010(tmp_path):
    """
    Happy path LLD commit | Auto | state with LLD files | Commit created,
    pushed | Commit SHA returned; files in remote
    """
    # TDD: Arrange
    created_files = ["docs/lld/active/LLD-162.md", "docs/lld/lld-status.json"]
    
    with patch("subprocess.run") as mock_run:
        # Mock git add (called twice)
        # Mock git commit
        # Mock git push
        mock_run.side_effect = [
            Mock(returncode=0, stdout="", stderr=""),  # git add file 1
            Mock(returncode=0, stdout="", stderr=""),  # git add file 2
            Mock(returncode=0, stdout="[main abc123] docs: add LLD-162 via requirements workflow\n", stderr=""),  # git commit
            Mock(returncode=0, stdout="", stderr=""),  # git push
        ]
        
        # TDD: Act
        commit_sha = commit_and_push(
            created_files=created_files,
            workflow_type="lld",
            target_repo=tmp_path,
            issue_number=162,
        )
        
        # TDD: Assert
        assert commit_sha == "abc123"
        assert mock_run.call_count == 4
        
        # Verify git add was called for each file
        assert mock_run.call_args_list[0][0][0] == ["git", "add", "docs/lld/active/LLD-162.md"]
        assert mock_run.call_args_list[1][0][0] == ["git", "add", "docs/lld/lld-status.json"]
        
        # Verify git commit (includes "Ref #N" footer - NOT "Closes" since LLD is design only)
        assert mock_run.call_args_list[2][0][0] == ["git", "commit", "-m", "docs: add LLD-162 via requirements workflow\n\nRef #162"]
        
        # Verify git push
        assert mock_run.call_args_list[3][0][0] == ["git", "push"]


def test_020(tmp_path):
    """
    Happy path issue commit | Auto | state with lineage files | Commit
    created, pushed | Commit SHA returned; message format correct
    """
    # TDD: Arrange
    created_files = ["docs/lineage/active/my-feature/001-final.md"]
    
    with patch("subprocess.run") as mock_run:
        mock_run.side_effect = [
            Mock(returncode=0, stdout="", stderr=""),  # git add
            Mock(returncode=0, stdout="[main def456] docs: add lineage for my-feature via requirements workflow\n", stderr=""),  # git commit
            Mock(returncode=0, stdout="", stderr=""),  # git push
        ]
        
        # TDD: Act
        commit_sha = commit_and_push(
            created_files=created_files,
            workflow_type="issue",
            target_repo=tmp_path,
            slug="my-feature",
        )
        
        # TDD: Assert
        assert commit_sha == "def456"
        
        # Verify commit message format (index 3 is the message after ["git", "commit", "-m", message])
        commit_call = mock_run.call_args_list[1]
        assert commit_call[0][0][3] == "docs: add lineage for my-feature via requirements workflow"


def test_030(tmp_path):
    """
    Empty created_files | Auto | state with empty list | No commit, no
    error | Function returns without git operations
    """
    # TDD: Arrange
    created_files = []
    
    with patch("subprocess.run") as mock_run:
        # TDD: Act
        commit_sha = commit_and_push(
            created_files=created_files,
            workflow_type="lld",
            target_repo=tmp_path,
            issue_number=162,
        )
        
        # TDD: Assert
        assert commit_sha == ""
        assert mock_run.call_count == 0


def test_040():
    """
    Commit message format - LLD | Auto | workflow_type="lld", issue=162 |
    Formatted message | Message includes title and "Ref #N" footer (NOT Closes)
    """
    # TDD: Arrange
    # (no setup needed)

    # TDD: Act
    message = format_commit_message("lld", issue_number=162)

    # TDD: Assert - message includes "Ref #N" (NOT "Closes" - LLD is design only)
    assert message == "docs: add LLD-162 via requirements workflow\n\nRef #162"


def test_050():
    """
    Commit message format - issue | Auto | workflow_type="issue",
    slug="my-feature" | Formatted message | Message matches `docs: add
    lineage for my-feature via requirements workflow`
    """
    # TDD: Arrange
    # (no setup needed)

    # TDD: Act
    message = format_commit_message("issue", slug="my-feature")

    # TDD: Assert
    assert message == "docs: add lineage for my-feature via requirements workflow"


def test_060(tmp_path):
    """
    Commit failure | Auto | Invalid repo state | GitOperationError raised |
    Error message contains "commit failed"
    """
    # TDD: Arrange
    created_files = ["docs/lld/active/LLD-162.md"]
    
    with patch("subprocess.run") as mock_run:
        mock_run.side_effect = [
            Mock(returncode=0, stdout="", stderr=""),  # git add succeeds
            Mock(returncode=1, stdout="", stderr="fatal: not a git repository"),  # git commit fails
        ]
        
        # TDD: Act & Assert
        with pytest.raises(GitOperationError) as exc_info:
            commit_and_push(
                created_files=created_files,
                workflow_type="lld",
                target_repo=tmp_path,
                issue_number=162,
            )
        
        assert "Failed to commit" in str(exc_info.value)


def test_070(tmp_path):
    """
    Push failure | Auto | Mock network error | GitOperationError raised |
    Error message contains "push failed"; local commit SHA in message
    """
    # TDD: Arrange
    created_files = ["docs/lld/active/LLD-162.md"]
    
    with patch("subprocess.run") as mock_run:
        mock_run.side_effect = [
            Mock(returncode=0, stdout="", stderr=""),  # git add
            Mock(returncode=0, stdout="[main abc123] message\n", stderr=""),  # git commit
            Mock(returncode=1, stdout="", stderr="fatal: unable to access 'https://...': Could not resolve host"),  # git push fails
        ]
        
        # TDD: Act & Assert
        with pytest.raises(GitOperationError) as exc_info:
            commit_and_push(
                created_files=created_files,
                workflow_type="lld",
                target_repo=tmp_path,
                issue_number=162,
            )
        
        error_msg = str(exc_info.value)
        assert "Failed to push" in error_msg
        assert "abc123" in error_msg  # Local commit SHA included


def test_080(tmp_path):
    """
    Selective staging | Auto | created_files + untracked file | Only
    created_files staged | Untracked file not in commit
    """
    # TDD: Arrange
    created_files = ["docs/lld/active/LLD-162.md"]
    # Simulate: there's also an untracked file "other.txt" in the repo
    # We verify that only the files in created_files are staged
    
    with patch("subprocess.run") as mock_run:
        mock_run.side_effect = [
            Mock(returncode=0, stdout="", stderr=""),  # git add (only our file)
            Mock(returncode=0, stdout="[main abc123] message\n", stderr=""),  # git commit
            Mock(returncode=0, stdout="", stderr=""),  # git push
        ]
        
        # TDD: Act
        commit_and_push(
            created_files=created_files,
            workflow_type="lld",
            target_repo=tmp_path,
            issue_number=162,
        )
        
        # TDD: Assert
        # Verify only the specified file was added (not other.txt)
        git_add_calls = [c for c in mock_run.call_args_list if c[0][0][1] == "add"]
        assert len(git_add_calls) == 1
        assert git_add_calls[0][0][0] == ["git", "add", "docs/lld/active/LLD-162.md"]


# Integration Tests
# -----------------

# test_090 (Issue #162 integration) was deleted with #1459. The LLD path
# of _commit_and_push_files now dispatches to setup_lld_worktree +
# commit_and_pr (worktree + PR) instead of direct push, which requires gh
# CLI access and a real GitHub remote — out of scope for a unit-level
# integration test. Mock-based coverage of the new dispatch lives in
# tests/unit/test_requirements_nodes.py::TestFinalizeNodeAdditional
# (test_commit_lld_dispatches_to_pr_path,
#  test_commit_issue_workflow_uses_legacy_push,
#  test_commit_lld_error_logged).


# Issue #1459 — LLD worktree + PR
# --------------------------------

def test_lld_worktree_path_for_appends_lld_suffix():
    """Worktree path is `{repo}/data/worktrees/{N}-lld`, distinct from impl's
    `{repo}/data/worktrees/{N}` so LLD and impl worktrees don't collide.

    Moved inside the repo's gitignored data/ by #2077; it used to be a sibling,
    which put a directory per roll into ~/Projects.
    """
    from assemblyzero.workflows.requirements.git_operations import lld_worktree_path_for

    path = lld_worktree_path_for("/c/Users/x/Projects/Chiron", 4)
    assert path.name == "4-lld"
    assert path.parent.name == "worktrees"
    assert path == Path("/c/Users/x/Projects/Chiron/data/worktrees/4-lld")


def test_commit_and_pr_returns_empty_for_empty_created_files():
    """No-op when nothing to commit (mirrors commit_and_push behavior)."""
    from assemblyzero.workflows.requirements.git_operations import commit_and_pr

    sha, url = commit_and_pr(
        created_files=[],
        worktree_path="/tmp/wt",
        target_repo="/tmp/target",
        issue_number=4,
        branch_name="4-lld",
        base_branch="main",
    )
    assert sha == ""
    assert url == ""


def _fake_git(seen: list[list[str]]):
    """A run_command that answers git and records every command. There is no
    gh branch: since #3704 nothing on this path may call gh."""
    from unittest.mock import MagicMock

    def fake_run(cmd, *args, **kwargs):
        seen.append(list(cmd))
        out = MagicMock()
        out.returncode = 0
        if cmd[:2] == ["git", "commit"]:
            out.stdout = "[4-lld abc123] commit message\n"
        elif cmd[:1] == ["git"] and "remote" in cmd:
            out.stdout = "https://github.com/owner/repo.git\n"
        else:
            out.stdout = ""
        return out

    return fake_run


def _fake_landing(captured: dict, pr_number: int = 9999):
    from assemblyzero.core.merge_driver import Landing

    def fake_land(**kwargs):
        captured.update(kwargs)
        captured["body"] = Path(kwargs["body_file"]).read_text(encoding="utf-8")
        return Landing(pr_number=pr_number, squash_sha="0123abcd", output="[OK] stage=landed")

    return fake_land


def test_commit_and_pr_emits_no_issue_for_pr_body(tmp_path):
    """The LLD PR body must contain `No-Issue:` (not `Closes #N`) so the
    referenced issue stays open through the implementation phase.
    Encodes the architectural decision from Issue #238. Since #3704 the PR
    is opened and merged by the fleet merge driver, which this test stands
    in for; nothing here pushes or calls gh."""
    from unittest.mock import patch
    from assemblyzero.workflows.requirements.git_operations import commit_and_pr

    captured: dict = {}
    seen: list[list[str]] = []

    target = tmp_path / "repo"
    target.mkdir()
    wt = tmp_path / "repo-4-lld"
    wt.mkdir()
    file_in_wt = wt / "docs" / "lld" / "active" / "LLD-004.md"
    file_in_wt.parent.mkdir(parents=True)
    file_in_wt.write_text("# LLD")

    with patch("assemblyzero.workflows.requirements.git_operations.run_command",
               side_effect=_fake_git(seen)), \
         patch("assemblyzero.workflows.requirements.git_operations.merge_driver.land",
               side_effect=_fake_landing(captured)):
        sha, url = commit_and_pr(
            created_files=[str(file_in_wt)],
            worktree_path=wt,
            target_repo=target,
            issue_number=4,
            branch_name="4-lld",
            base_branch="main",
        )

    assert sha == "abc123"
    assert url == "https://github.com/owner/repo/pull/9999"
    body, title = captured["body"], captured["title"]
    assert "No-Issue:" in body, f"PR body must contain No-Issue: — got {body!r}"
    assert "Closes #4" not in body, f"LLD PR must NOT close — got {body!r}"
    assert "Closes #4" not in title, f"LLD PR title must NOT close — got {title!r}"
    assert "Ref #4" in title, f"PR title should reference — got {title!r}"
    assert captured["no_issue"] is True
    assert captured["worktree"] == wt and captured["branch"] == "4-lld"
    assert not any(c[:1] == ["gh"] for c in seen), f"gh was called: {seen}"
    assert not any(c[:2] == ["git", "push"] for c in seen), (
        "nothing is pushed before the driver runs (#3704)"
    )


def test_commit_and_pr_targets_given_base_branch(tmp_path):
    """#1754 attempt-branch model: the PR base is the integration branch
    captured at invocation, never a hardcoded main. On a speedrun the
    target repo stands on `speedrun-attempt-N` and the LLD PR must
    target it."""
    from unittest.mock import patch
    from assemblyzero.workflows.requirements.git_operations import commit_and_pr

    captured: dict = {}
    wt = tmp_path / "repo-4-lld"
    wt.mkdir()
    lld = wt / "LLD-004.md"
    lld.write_text("# LLD")

    with patch("assemblyzero.workflows.requirements.git_operations.run_command",
               side_effect=_fake_git([])), \
         patch("assemblyzero.workflows.requirements.git_operations.merge_driver.land",
               side_effect=_fake_landing(captured, pr_number=1)):
        commit_and_pr(
            created_files=[str(lld)],
            worktree_path=wt,
            target_repo=tmp_path / "repo",
            issue_number=4,
            branch_name="4-lld",
            base_branch="speedrun-attempt-1",
        )

    assert captured["base"] == "speedrun-attempt-1", (
        f"PR must target the captured integration branch — got {captured['base']!r}"
    )
    assert "speedrun-attempt-1" in captured["body"], (
        "PR body should name the branch the LLD lands on"
    )
    assert "land it on main" not in captured["body"]


def test_commit_and_pr_reports_the_drivers_refusal_and_pushes_nothing(tmp_path):
    """A refused landing is a GitOperationError carrying the driver's own
    words, and the branch was never pushed (#3704)."""
    from unittest.mock import patch
    from assemblyzero.core.merge_driver import MergeDriverError
    from assemblyzero.workflows.requirements.git_operations import (
        GitOperationError,
        commit_and_pr,
    )

    seen: list[list[str]] = []
    wt = tmp_path / "repo-4-lld"
    wt.mkdir()
    (wt / "LLD-004.md").write_text("# LLD")

    def refusing_land(**kwargs):
        raise MergeDriverError("PRE-FLIGHT FAILED: parasitic directive in body")

    with patch("assemblyzero.workflows.requirements.git_operations.run_command",
               side_effect=_fake_git(seen)), \
         patch("assemblyzero.workflows.requirements.git_operations.merge_driver.land",
               side_effect=refusing_land), \
         pytest.raises(GitOperationError, match="PRE-FLIGHT FAILED"):
        commit_and_pr(
            created_files=[str(wt / "LLD-004.md")],
            worktree_path=wt,
            target_repo=tmp_path / "repo",
            issue_number=4,
            branch_name="4-lld",
            base_branch="main",
        )
    assert not any(c[:2] == ["git", "push"] for c in seen)


# Issue #238 - Ref instead of Closes
# -----------------------------------

def test_format_commit_message_lld_uses_ref_not_closes():
    """LLD commits should reference issues, not close them."""
    message = format_commit_message("lld", issue_number=173)

    assert "Ref #173" in message, "Should use 'Ref' to reference issue"
    assert "Closes #173" not in message, "Should NOT close issue - LLD is design only"
    assert "closes #173" not in message.lower(), "Case-insensitive check"


def test_format_commit_message_issue_uses_ref_not_closes():
    """Issue brief commits should reference issues, not close them."""
    message = format_commit_message("issue", issue_number=99, slug="my-feature")

    assert "Closes #" not in message, "Issue workflow should not close issues"